# FOLIO Release Configuration
# This file defines the variants and file requirements for FOLIO release artifacts

variants:
  minimal:
    description: "Minimal FOLIO platform release with core files only"
    required_files:
      - "platform-descriptor.json"
      - "package.json"
      - "yarn.lock"
    optional_files:
      - "README.md"
      - "LICENSE"
      - "stripes.config.js"
    include_module_descriptors: false
    collect_from_mgr_applications: false

  complete:
    description: "Complete FOLIO platform release with all files and descriptors"
    required_files:
      - "platform-descriptor.json"
      - "package.json"
      - "yarn.lock"
      - "stripes.config.js"
      - "stripes.*.js"
    optional_files:
      - "README.md"
      - "LICENSE"
      - "docker/"
      - "tenant-assets/"
      - "output/"
    include_module_descriptors: true
    collect_from_mgr_applications: true

# Global settings
settings:
  max_archive_size_mb: 500
  mgr_applications_timeout: 30
  archive_format: "tar.gz"

# File patterns to exclude from all variants
exclude_patterns:
  - "node_modules/"
  - ".git/"
  - ".github/"
  - "*.log"
  - "*.tmp"
  - ".DS_Store"
  - "Thumbs.db"
