update_config:
  enabled: true
  update_branch_format: version-update/{0}
  labels:
    - version-update
  pr_reviewers:
    - folio-org/kitfox

branches:
  - R1-1994:
      enabled: true
      need_pr: true
      pre_release: "false"
