update_config:
  enabled: true
  update_branch_format: version-update/{0}
  labels:
    - version-update
  pr_reviewers:
    - folio-org/kitfox

branches:
  - snapshot:
      enabled: false
      name: "FOLIO Sunflower Version"
      description: "FOLIO Snapshot LSP (Library Services Platform) is a set of microservices and applications that provide a complete library management system."
      need_pr: false
      pre_release: "only"
  - R1-1994:
      enabled: true
      name: "FOLIO R1-1994 Version"
      description: "FOLIO R1-1994 is a major release that includes significant updates and new features for the FOLIO platform."
      need_pr: true
      pre_release: "false"