// Settings-only plugins for Stripes. Always listed alphabetically, if at all
module.exports = {
  '@folio/acquisition-units': {},
  '@folio/authorization-policies': {},
  '@folio/calendar' : {},
  '@folio/circulation' : {},
  '@folio/developer' : {},
  '@folio/handler-stripes-registry': {},
  "@folio/gobi-settings": {},
  '@folio/myprofile' : {},
  '@folio/notes' : {},
  '@folio/oai-pmh' : {},
  '@folio/plugin-bursar-export': {},
  '@folio/plugin-create-inventory-records' : {},
  '@folio/plugin-find-agreement' : {},
  '@folio/plugin-find-authority' : {},
  '@folio/plugin-find-erm-usage-data-provider' : {},
  '@folio/plugin-find-fund' : {},
  '@folio/plugin-eusage-reports': {},
  '@folio/plugin-find-import-profile' : {},
  '@folio/plugin-find-instance' : {},
  '@folio/plugin-find-contact' : {},
  '@folio/plugin-find-eresource': {},
  '@folio/plugin-find-interface' : {},
  '@folio/plugin-find-license' : {},
  '@folio/plugin-find-organization' : {},
  '@folio/plugin-find-package-title': {},
  '@folio/plugin-find-po-line': {},
  '@folio/plugin-find-user' : {},
  '@folio/plugin-query-builder' : {},
  '@folio/quick-marc' : {},
  '@folio/service-interaction': {},
  '@folio/servicepoints' : {},
  '@folio/stripes-authority-components' : {},
  '@folio/stripes-erm-components' : {},
  '@folio/stripes-inventory-components' : {},
  '@folio/stripes-marc-components' : {},
  '@folio/tags' : {},
  '@folio/tenant-settings' : {},
};
