// User visible apps configuration for Stripes
module.exports = {
  '@folio/agreements' : {},
  '@folio/bulk-edit': {},
  '@folio/checkin' : {},
  '@folio/checkout' : {},
  '@folio/circulation-log' : {},
  '@folio/claims' : {},
  '@folio/courses' : {},
  '@folio/dashboard' : {},
  '@folio/data-export' : {},
  '@folio/data-import' : {},
  '@folio/eholdings' : {},
  '@folio/erm-comparisons': {},
  '@folio/erm-usage' : {},
  '@folio/export-manager': {},
  '@folio/finance' : {},
  '@folio/inn-reach' : {},
  '@folio/inventory' : {},
  '@folio/invoice' : {},
  '@folio/licenses' : {},
  '@folio/lists' : {},
  '@folio/local-kb-admin': {},
  '@folio/marc-authorities': {},
  '@folio/mosaic-settings': {},
  '@folio/requests-mediated' : {},
  '@folio/oa' : {},
  '@folio/orders' : {},
  '@folio/organizations' : {},
  '@folio/reading-room' : {},
  '@folio/receiving' : {},
  '@folio/remote-storage' : {},
  '@folio/ldp' : {},
  '@folio/requests' : {},
  '@folio/serials-management': {},
  '@folio/users' : {},
};
