name: 'Build PR Body'
description: 'Builds a formatted PR body with collapsed diff reports for platform updates'
author: 'FOLIO DevOps'

inputs:
  new_version:
    description: 'New platform version (or empty if no version change)'
    required: false
    default: ''
  updates_cnt:
    description: 'Total count of updates'
    required: false
    default: '0'
  updates_markdown:
    description: 'Markdown content for application & component updates'
    required: false
    default: ''
  ui_updates_markdown:
    description: 'Markdown content for UI dependency updates'
    required: false
    default: ''
  missing_ui_markdown:
    description: 'Markdown content for missing UI dependencies'
    required: false
    default: ''
  release_branch:
    description: 'Base/release branch name'
    required: true
  update_branch:
    description: 'Head/update branch name'
    required: true

outputs:
  pr_body:
    description: 'Formatted PR body with all sections and collapsed reports'
    value: ${{ steps.build.outputs.pr_body }}

runs:
  using: 'composite'
  steps:
    - name: 'Build PR body content'
      id: build
      shell: bash
      env:
        NEW_VERSION: ${{ inputs.new_version }}
        UPDATES_CNT: ${{ inputs.updates_cnt }}
        UPDATES_MARKDOWN: ${{ inputs.updates_markdown }}
        UI_UPDATES_MARKDOWN: ${{ inputs.ui_updates_markdown }}
        MISSING_UI_MARKDOWN: ${{ inputs.missing_ui_markdown }}
        RELEASE_BRANCH: ${{ inputs.release_branch }}
        UPDATE_BRANCH: ${{ inputs.update_branch }}
      run: |
        set -euo pipefail
        IFS=$'\n\t'

        version_display="${NEW_VERSION:-No version change}"
        count_display="${UPDATES_CNT:-0}"

        # Build complete PR body with collapsed report
        pr_body=$(cat <<EOF
        ## Automated Release Update

        **Base branch:** ${RELEASE_BRANCH}
        **Head branch:** ${UPDATE_BRANCH}
        **Platform version:** ${version_display}
        **Total changes:** ${count_display}

        ---

        ${UPDATES_MARKDOWN:-### Application & Component Updates

        No applications or eureka components were updated.}

        ---

        ${UI_UPDATES_MARKDOWN:-### UI Dependency Updates

        No UI dependencies were updated.}

        ---

        ${MISSING_UI_MARKDOWN:-### Missing UI Dependencies

        No missing UI dependencies detected.}

        ---

        > This PR description is auto-generated from a collapsed diff between the base and head branches.
        > Re-running the workflow with the same base/head state produces an identical description.
        EOF
        )

        {
          echo 'pr_body<<EOF'
          echo "$pr_body"
          echo 'EOF'
        } >> "$GITHUB_OUTPUT"

        echo "::notice::Built collapsed PR body (${#pr_body} bytes)"

