name: Release update (Reusable)

run-name: ${{ inputs.release_branch }} release update

on:
  workflow_call:
    inputs:
      release_branch:
        description: 'Release branch to scan'
        required: true
        type: string
      update_branch:
        description: 'Update branch name for this release branch'
        required: true
        type: string
      dry_run:
        description: 'Perform dry run without creating PRs'
        required: false
        type: boolean
        default: false
      pr_reviewers:
        description: 'Comma-separated list of reviewers'
        required: false
        type: string
        default: ''
      pr_labels:
        description: 'Comma-separated list of labels'
        required: false
        type: string
        default: ''
    outputs:
      scan_result:
        description: 'Result of the scan (success/failure/skipped)'
        value: ${{ jobs.scan.result }}
      updated:
        description: 'Whether updates were found'
        value: ${{ jobs.scan.outputs.updated }}
      pr_created:
        description: 'Whether a PR was created'
        value: ${{ jobs.scan.outputs.pr_created }}
      pr_url:
        description: 'URL of the created PR'
        value: ${{ jobs.scan.outputs.pr_url }}
      pr_number:
        description: 'PR number if created or updated'
        value: ${{ jobs.scan.outputs.pr_number }}
      workflow_status:
        description: 'Overall workflow status'
        value: ${{ jobs.scan.outputs.workflow_status }}
      failure_reason:
        description: 'Reason for workflow failure if any'
        value: ${{ jobs.scan.outputs.failure_reason }}
      new_version:
        description: 'New platform version if updated'
        value: ${{ jobs.scan.outputs.new_version }}
      updates_cnt:
        description: 'Number of modules/components updated'
        value: ${{ jobs.scan.outputs.updates_cnt }}

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: release-scan-${{ github.repository }}-${{ inputs.release_branch }}
  cancel-in-progress: false

jobs:
  hello-world:
    name: Hello World
    runs-on: ubuntu-latest
    steps:
      - name: Hello world action step
        uses: actions/hello-world-javascript-action@v1