name: Reusable Application Preparation Worker
on:
  workflow_call:
    inputs:
      application:
        required: true
        type: string
        description: 'Application name (e.g., app-agreements)'
      previous_release_version:
        required: true
        type: string
        description: 'Previous release version'
      new_release_name:
        required: true
        type: string
        description: 'New release name'
      dry_run:
        required: false
        type: boolean
        default: true
        description: 'Perform dry run without making changes'
      use_snapshot_fallback:
        required: false
        type: boolean
        default: true
        description: 'Use snapshot versions if release versions not found'
    outputs:
      status:
        description: 'Workflow execution status'
        value: ${{ jobs.call-app-workflow.outputs.status }}
      app_version:
        description: 'Determined application version'
        value: ${{ jobs.call-app-workflow.outputs.app_version }}
      changes_made:
        description: 'Whether changes were made'
        value: ${{ jobs.call-app-workflow.outputs.changes_made }}

jobs:
  call-app-workflow:
    name: 'Call ${{ inputs.application }} Workflow'
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.capture-outputs.outputs.status }}
      app_version: ${{ steps.capture-outputs.outputs.app_version }}
      changes_made: ${{ steps.capture-outputs.outputs.changes_made }}
    
    steps:
      - name: 'Call Application Release Preparation'
        id: call-release-prep
        uses: folio-org/${{ inputs.application }}/.github/workflows/release-preparation.yml@RANCHER-2320
        with:
          previous_release_version: ${{ inputs.previous_release_version }}
          new_release_name: ${{ inputs.new_release_name }}
          dry_run: ${{ inputs.dry_run }}
          use_snapshot_fallback: ${{ inputs.use_snapshot_fallback }}
      
      - name: 'Capture Outputs'
        id: capture-outputs
        run: |
          # Capture outputs from the called workflow
          echo "status=${{ steps.call-release-prep.outputs.status || 'success' }}" >> "$GITHUB_OUTPUT"
          echo "app_version=${{ steps.call-release-prep.outputs.app_version || '1.0.0-SNAPSHOT' }}" >> "$GITHUB_OUTPUT"
          echo "changes_made=${{ steps.call-release-prep.outputs.changes_made || 'true' }}" >> "$GITHUB_OUTPUT" 